### ISSUE TITLE
Finding out the partition

### ISSUE THREAD

**Issue by Krarilotus** [saref/frustration-index-XOR#1]
Dear Researcher,

i hope i am not too late with my question. I am very interested in using your approach for calculating fruststration indices in medival-social networks. Would it also be possible to find out the exact partition that lead to a specific fruststration index through the gurobi model?
Even if you know where i could look to find this information, i'd appriciate the hint!

Best regards and much respect for your work!
Johannes

**Comment by saref** [comment]
Hi Johannes,

You can certainly get the exact partition associated with the frustration index. For modifying the code to provide this, you can replace this part:

```
    # Printing the solution (optional)
    #print("Optimal values of the decision variables")
    #for v in model.getVars():
    #    print (v.varName, v.x)
    #print()    
```
	
with this:
	
```
    # Printing the solution (optional)
    print("Optimal values of the decision variables")
    for v in model.getVars():
	if v.varName.startswith('x'):
		print (v.varName, v.x)
    print()    	
```

Then, you will get the optimal values for all the x_i variables (binary decision variable associated with node i). x_i taking value 1 means  node i belongs to cluster 1 (and value 0 means belonging to cluster 0).

**Comment by Krarilotus** [comment]
Thank you so much, this really helped me and was exactly what i was looking for!
